In [2]:
import numpy as np

MatA = np.array([[2, 4, 6],
                 [8, 10, 12]])

MatB = np.array([[3, 3, 3],
                 [6, 6, 6],
                 [9, 9, 9]])

print("Matrix A:\n", MatA)
print("Matrix B:\n", MatB)

print("Shape of A:", MatA.shape)
print("Shape of B:", MatB.shape)

productAB = np.dot(MatA, MatB)
print("Product of A and B:\n", productAB)

Matrix A:
 [[ 2  4  6]
 [ 8 10 12]]
Matrix B:
 [[3 3 3]
 [6 6 6]
 [9 9 9]]
Shape of A: (2, 3)
Shape of B: (3, 3)
Product of A and B:
 [[ 84  84  84]
 [192 192 192]]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transpose_arr = arr.T
print(transpose_arr)

[[1 4]
 [2 5]
 [3 6]]


In [7]:
import numpy as np

mat_a = np.array([[1, 2], [3, 4]])
mat_b = np.array([[5, 6], [7, 8]])

result_add = np.add(mat_a, mat_b)
result_sub = np.subtract(mat_a, mat_b)
res_elem = np.multiply(mat_a, mat_b)
res_dot = np.dot(mat_a, mat_b)
res_trans = np.transpose(mat_a)

print("Sum:", result_add)
print("Difference:", result_sub)
print("Product:", res_elem)
print("Dot:", res_dot)
print("Transpose of Matrix:", res_trans)

Sum: [[ 6  8]
 [10 12]]
Difference: [[-4 -4]
 [-4 -4]]
Product: [[ 5 12]
 [21 32]]
Dot: [[19 22]
 [43 50]]
Transpose of Matrix: [[1 3]
 [2 4]]
